version: 0.0
os: windows
files:
  - source: \"*.html"
    destination: C:\inetpub\wwwroot
  - source: \"*.html"
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
