version: 0.0
os: windows
files:
  - source: \"*.html"
    destination: C:\inetpub\wwwroot
  - source: \"VineUp com home page"
    destination: C:\inetpub\wwwroot\"VineUp com home page"
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
  AfterInstall:
    - location: \after-install.bat
      timeout: 900
